SHELL := /bin/bash
LUTAML_BUNDLE := BUNDLE_GEMFILE=Gemfile.lutaml

# Packages that build LXR but skip SPA generation (known xsdvi bugs)
SPA_SKIP  :=

all: configs lxr-spas _site

# Generate per-schema config files, index JSON, and Makefile.spa
schemas_index.json: generate_configs.rb
	ruby generate_configs.rb

configs: schemas_index.json ;

# Build all LXR + SPA packages
lxr-spas: configs
	$(MAKE) build-all

build-all:
	$(MAKE) -j4 $(LXR_FILES) $(SPA_OK)

CONFIGS   := $(wildcard configs/*.yml)
LXR_FILES := $(patsubst configs/%.yml,build/%.lxr,$(CONFIGS))
SPA_OK    := $(filter-out $(foreach s,$(SPA_SKIP),site/$(s).html),)

# Build a single LXR package from a config
build/%.lxr: configs/%.yml
	mkdir -p build
	$(LUTAML_BUNDLE) bundle exec lutaml-xsd build from-config $< \
		--output $@

# SPA build rules (auto-generated by generate_configs.rb)
-include configs/Makefile.spa

# Build Jekyll site
_site: lxr-spas
	JEKYLL_ENV=production bundle exec jekyll build

# Dev server
serve:
	bundle exec jekyll serve

clean:
	rm -rf build site _site configs schemas_index.json resources_index.json

distclean: clean
	rm -rf schemas/_site

update-init:
	git submodule update --init

update-modules:
	git submodule foreach git checkout main
	git submodule foreach git pull origin main

.PHONY: all configs build-all lxr-spas clean distclean serve update-init update-modules
