SHELL := /bin/bash
LUTAML_BUNDLE := BUNDLE_GEMFILE=schemas/Gemfile BUNDLE_PATH=vendor/bundle-lutaml

all: configs lxr-spas _site

# Generate per-schema config files and index JSON
configs:
	ruby generate_configs.rb

# Build all LXR + SPA packages
lxr-spas: configs
	@GEM_DIR=$$($(LUTAML_BUNDLE) bundle show lutaml-jsonschema 2>/dev/null) && \
		[ -d "$$GEM_DIR/frontend/dist" ] || { cd "$$GEM_DIR/frontend" && npm install && npm run build; } || true
	$(MAKE) -j4 $(LXR_FILES) $(SPA_FILES)

CONFIGS   := $(wildcard configs/*.yml)
LXR_FILES := $(patsubst configs/%.yml,build/%.lxr,$(CONFIGS))
SPA_FILES :=

build/%.lxr: configs/%.yml
	mkdir -p build
	$(LUTAML_BUNDLE) bundle exec lutaml-xsd build from-config $< \
		--output $@

# SPA build rules (auto-generated by generate_configs.rb)
-include configs/Makefile.spa

# Build Jekyll site (SPA pages + schema data registered by BuildSourceGenerator plugin)
_site: lxr-spas
	JEKYLL_ENV=production bundle exec jekyll build

serve:
	bundle exec jekyll serve

clean:
	rm -rf build site _site configs schemas_index.json resources_index.json

update:
	git -C schemas pull || git clone --depth 1 https://github.com/ISO-TC211/schemas.git schemas

.PHONY: all configs lxr-spas clean serve update
