import 'theme-css/header.css'
import 'theme-css/footer.css'
import 'theme-css/typography.css'
import 'theme-css/page.css'
import 'theme-js/theme.js'
import '../css/schemas.css'
import '../js/schemas.js'
import '../js/resources.js'
