---
layout: home
permalink: /

extra_scripts:
  - src: /assets/js/locator.js
---
:page-liquid:

[.section.locator]
== Locate specific schemas

Each ISO/TC 211 schema is identified by a URI of the following pattern:

[source]
----
https://schemas.isotc211.org/{StandardNumber}/{PartNumber}/{NamespacePrefix}/{Version}
----

NOTE: When a standard has no part number, the character `-` (dash-hyphen) is
used for `{PartNumber}`.

[example]
.Examples of schema information URIs
====
* ISO 19110:2005 `fcc` v1.0: link:19110/fcc/1.0/[]
* ISO 19115-3:2016 `cit` 1.0: link:19115/-3/cit/1.0[]
* ISO/TS 19157-2:2016 `mdq` 1.0: link:19157/-2/mdq/1.0[]
====

[.section]
== Resources

* link:/docs[Schema documentation]

* link:/schemas[Browse schemas and associated resources]

* link:/transforms[Supporting transformations]


[.section]
== Maintenance

Comments, suggestions, change requests and revisions
are managed in the https://github.com/ISO-TC211/XML[GitHub repository]
for the ISO/TC 211 XML Maintenance Group (XMG).

For more information, please visit
https://committee.iso.org/home/tc211[ISO/TC 211 committee page]
and https://www.isotc211.org/[ISO/TC 211 resources site].

This site is managed by ISO/TC 211 XMG and Ribose.


++++
<template id="schemaLocator">
  <form>
    <div class="input">
      <label for="schemaStandardNumber">Standard number</label>
      <input id="schemaStandardNumber" type="text" placeholder="For example, 19115" name="standardNumber">
    </div>
    <div class="input">
      <label for="schemaPartNumber">Part number</label>
      <input id="schemaPartNumber" type="text" placeholder="3" name="partNumber">
    </div>
    <div class="input">
      <label for="schemaNsPrefix">Namespace prefix</label>
      <input id="schemaNsPrefix" type="text" placeholder="cit" name="nsPrefix">
    </div>
    <div class="input">
      <label for="schemaVersion">Version</label>
      <input id="schemaVersion" type="text" placeholder="1.0" name="version">
    </div>
    <div class="actions">
      <button type="button" name="locate">Locate schema</button>
    </div>
  </form>
</template>
++++
