---
title: Transformations for ISO/TC 211 XML schemas
layout: page
permalink: /transforms/
---
ISO/TC 211 provides ready-to-use transformation scripts to facilitate user
migration to newer versions of standards.

Resources on this page are organized by standard identifiers.

== ISO 19115-3:2022

The ISO/TC 211 XMG provides 2 XSLT scripts for users using previous version
of ISO 19115-3 XML schemas to migrate to the current schema.

The current version of the ISO 19115-3 XML schema is v1.3. It corresponds
to ISO 19115-3:2022, ISO 19115-1:2014 and ISO 19115-2:2019.

The `transforms/19115-3-2016-2022` directory contains the XSLTs to convert
ISO 19115-3:2016 XML (v1.0 and v2.0) instance documents into ISO 19115-3 v1.3
and ISO 19115-1 and ISO 19115-2:.

* Convert XML records from 19115-3 v1.0 to v1.3:
** File name: `ISO191115-3V1.0_Call_NamespaceUpdateThenReorder.xsl`
** URL: `https://schemas.isotc211.org/schemas/19115/resources/transforms/19115-3-2016-2022/ISO19115-3V1.0_Call_NamespaceUpdateThenReorder.xsl`

* Convert XML records from 19115-3 v2.0 to v1.3:
** File name: `ISO191115-3V2.0_Call_NamespaceUpdateThenReorder.xsl`
** URL: `https://schemas.isotc211.org/schemas/19115/resources/transforms/19115-3-2016-2022/ISO19115-3V2.0_Call_NamespaceUpdateThenReorder.xsl`


To use these XSLT files online:

* Please directly refer to the URLs specified above, as these transformation
files also refer to other component files provided in the same directory.

To use these XSLT files offline:

* Download the full set of scripts as a single ZIP file:
link:/schemas/19115/resources/transforms/19115-3-2016-2022.zip[`19115-3-2016-2022.zip`]


// link:/schemas/19115/resources/transforms/CT_CodelistCatalougue2HTML.xsl[CT_CodelistCatalougue2HTML.xsl]
